### ISSUE TITLE
error after launching ./rbkit

### ISSUE THREAD

**Issue by scicco** [code-mancers/rbkit#101]
I've grabbed the tar and installed on my ubuntu machine

./RbkitClient: 9: ./RbkitClient: Syntax error: ")" unexpected

checked site and installed ruby 2.1 with rvm. Set it as default and tried again. Same result. Any advice?

**Comment by gnufied** [comment]
Is this 32bit machine? The executable will only work on 64bit machines.

**Comment by scicco** [comment]
oh, i see...you're right, i'm on 32bit :cry:

**Comment by gnufied** [comment]
Yeah, sorry about it. We haven't got around to setting up build environment of our desktop app (https://github.com/code-mancers/rbkit-client) on a 32bit Linux machine.  This is a known problem which will fix in future. In the meanwhile, if you are up for it - you can compile the desktop app yourself and give it a go.
