### ISSUE TITLE
Figure out API for CPU profiling

### ISSUE THREAD

**Issue by gnufied** [code-mancers/rbkit#107]
We should figure out API for CPU profiling.

**Comment by emilsoman** [comment]
@gnufied  `start_cpu_profile` and `stop_cpu_profile` commands have been added as part of the initial version of CPU profiling. See [commit](https://github.com/code-mancers/rbkit/commit/73d51b69d05248f8474bf8f0b50eae947709b5ef#diff-0f76de766893550a080f0e24bda8b7deR59).

**Comment by gnufied** [comment]
Okay, but I was thinking more about event format. What will be sent and how often etc.

**Comment by emilsoman** [comment]
Event format implemented in #124
