### ISSUE TITLE
sometimes i see huge reallocs during objectdump.

### ISSUE THREAD

**Issue by iffyuva** [code-mancers/rbkit#50]
i ran `using_rbkit.rb` for 4 hours. then i requested for obj snapshot.
i had put traces for *allocs, and i could see this:

```
malloc size 14860e90:8 
realloc size 2c456000:268435456
realloc size c4b3000:137281241
```

so, at one point rbkit is requesting for 268mb of memory. maybe we should look into fragmenting object dump.

**Comment by emilsoman** [comment]
Fixed by #77
